#!/usr/bin/env bash
# Script that will display information about subdomains
# domains and subdomains to be passed as arguments to script

# function to extract domain and subdomain details from dig

findRecords ()
{
    r_type="$(dig ${2}.${1} | awk 'NR==14 { print $4 }')"
    ip_add="$(dig ${2}.${1} | awk 'NR==14 { print $5 }')"

    echo "The subdomain $2 is a $r_type record and points to $ip_add"
}

if [ "$#" -ne 2 ];
then
    findRecords $1 "www"
    findRecords $1 "lb-01"
    findRecords $1 "web-01"
    findRecords $1 "web-02"
else
    findRecords $1 $2
fi
