#!/usr/bin/env bash
# script that transfers a file from client to server

num=3

if [ "$#" -lt "$num" ]
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
    sudo sed -i 's/StrictHostKeyChecking */StrictHostKeyChecking no/' /etc/ssh/ssh_config
    scp -i "$4" "$1" "$3"@"$2":~/
fi
